### ISSUE TITLE
演练场和文档打开都是空白的。

### ISSUE THREAD

**Issue by Hard-workingrookie** [tal-tech/electron-playground#32]
# 🐞 bug report
![image](https://user-images.githubusercontent.com/51024834/103781179-f3b1b100-5070-11eb-82b0-0b1e3884c10a.png)
![image](https://user-images.githubusercontent.com/51024834/103781304-1d6ad800-5071-11eb-89b1-88ecba4e8694.png)

## Environment

Platform: 
OS Version:

**Comment by ivyhaswell** [comment]
确认是bug，预计今天修复

**Comment by ivyhaswell** [comment]
快速启动example目录结构不对导致的问题，已修复

**Comment by Elors** [comment]
遇到同样的问题，看起来还是目录结构导致的？
<img width="1624" alt="image" src="https://user-images.githubusercontent.com/13915173/104680115-20795e80-572a-11eb-9eec-857705b22687.png">

**Comment by ivyhaswell** [comment]
@Elors 请问操作步骤是？我这边没有复现呢

**Comment by Elors** [comment]
> @Elors 请问操作步骤是？我这边没有复现呢

1. `n v12.0.0`    切换node版本（部分依赖库需求）
2. `yarn`    安装依赖
3. `yarn start`    启动
4. 输入`open api`    打开 交互式api文档面板
4. 启动后点击任意目录

**Platform: Mac
OS Version: MacOS Big Sur 11.1**

我注意到右侧调试信息里的路径带有“/Users/wangshuwen/”这个用户目录，猜测是开发环境的路径？

**Comment by ivyhaswell** [comment]
@Elors 
嗯嗯我知道问题了，马上修复一波

**Comment by ivyhaswell** [comment]
已经修复
